wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728442354
    t:
      1:
      - 1
      - 50
      - 55
      - 77
      - 105
      2:
      - 1
      - 50
      - 55
      - 77
      - 105
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.19
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
batch_size:
  desc: null
  value: 512
val_batch_size:
  desc: null
  value: null
test_batch_size:
  desc: null
  value: null
train_data_size:
  desc: null
  value: 1000
val_data_size:
  desc: null
  value: 100
test_data_size:
  desc: null
  value: 10000
optimizer:
  desc: null
  value: Adam
optimizer_kwargs:
  desc: null
  value:
    lr: 0.0001
lr_scheduler:
  desc: null
  value: null
lr_scheduler_kwargs:
  desc: null
  value:
    milestones:
    - 80
    - 95
    gamma: 0.1
lr_scheduler_interval:
  desc: null
  value: epoch
lr_scheduler_monitor:
  desc: null
  value: val/reward
generate_default_data:
  desc: null
  value: false
shuffle_train_dataloader:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 2
data_dir:
  desc: null
  value: data/
log_on_step:
  desc: null
  value: true
metrics:
  desc: null
  value: {}
baseline:
  desc: null
  value: rollout
baseline_kwargs:
  desc: null
  value: {}
reward_scale:
  desc: null
  value: null
policy_kwargs:
  desc: null
  value: {}
