wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728366523
    t:
      1:
      - 1
      - 50
      - 55
      - 77
      2:
      - 1
      - 50
      - 55
      - 77
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.15
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
